config/routes.rb
Rails.application.routes.draw do

  get 'no_admin/show'

  devise_for :users, :controllers => {
      :omniauth_callbacks => "omniauth_callbacks",
      :registrations => 'users/registrations',
      :sessions => 'users/sessions'
  }

  root 'landing#home'

  namespace :landing do
    resources :hairstyles, only: [:index, :show] do
      resources :offices, only: [:index] do
        member do
          get :checkout
        end
      end
    end

    resources :makeups, only: [:index, :show] do
      resources :offices, only: [:index] do
        get :checkout
      end
    end

    resources :nails, only: [:index, :show] do
      resources :offices, only: [:index] do
        get :checkout
      end
    end

  end


  namespace :admin do
    resources :offices
    resources :employees
    resources :hairstyles
    resources :makeups
    resources :nails
  end

end

app/models/nail.rb
class Nail < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300#", thumb: "100x100#" }, default_url: "nails.jpg",
                    :url => ':s3_domain_url', :path => '/:class/:attachment/:id_partition/:style/:filename'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_presence_of :name, :duration, :cost, :detail
end

app/controllers/admin/nails_controller.rb
class Admin::NailsController < ApplicationController
  include AdminValidation
  before_action :authenticate_user!, :is_admin?
  before_action :get_nail, except: [:index, :create, :new]

  def index
    @nails = Nail.all
  end

  def new
    @nail = Nail.new
  end

  def create
    @nail = Nail.new(nail_params)

    if @nail.save
      redirect_to [:admin, @nail]
    else
      render new_admin_nail_path
    end
  end

  def show
  end

  def edit
  end

  def update
    @nail.update(nail_params)
    if @nail.persisted?
      flash[:notice] = "Se ha actualizado exitosamente"
      redirect_to admin_nails_path
    end
  end


  def destroy
    @nail.destroy!
    redirect_to admin_nails_path
  end

  private

  def get_nail
    @nail = Nail.find(params[:id])
  end

  def nail_params
    params.require(:nail).permit(:name, :duration, :cost, :detail, :image)
  end
end

app/controllers/landing/nails_controller.rb
class Landing::NailsController < ApplicationController
  layout 'salon'

  def index
    @nails = Makeup.all
  end
end

app/views/admin/nails/_form.html.haml
.container
  .well
    = form_for([:admin, @nail], html: { class: 'form-horizontal' }) do |f|
      .form-group
        = f.label 'Nombre'
        = f.text_field :name, class: 'form-control'

      .form-group
        = f.label 'Duración'
        = f.text_field :duration, class: 'form-control'

      .form-group
        = f.label 'Costo'
        = f.text_field :cost, class: 'form-control'

      .form-group
        = f.label 'Detalle'
        = f.text_area :detail, class: 'form-control'

      .form-group
        = f.label 'Imagen'
        = f.file_field :image

      = f.submit 'Guardar', class: 'btn btn-success'

app/views/admin/nails/edit.html.haml
.row
  .col-lg-12
    %h1.page-header Editar uñas
    %ol.breadcrumb
      %li.active
        %i.fa.fa-scissors Uñas

    = render 'form'

app/views/admin/nails/index.html.haml
.row
  .col-lg-12
    %h1.page-header Lista de uñas
    %ol.breadcrumb
      %li.active
        %i.fa.fa-scissors Uñas

    .table-responsive
      %table.table.table-bordered.table-hover.table-striped
        %thead
          %tr
            %th
            %th Nombre
            %th Duración
            %th Costo
            %th Detalle
        %tbody

        %tbody
          - @nails.each do |n|
            %tr
              %td
                = image_tag n.image(:thumb)
              %td
                = link_to n.name, admin_nails_path(n)
              %td
                = n.duration
              %td
                = n.cost
              %td
                = n.detail

app/views/admin/nails/new.html.haml
.row
  .col-lg-12
    %h1.page-header Crear Uñas
    %ol.breadcrumb
      %li.active
        %i.fa.fa-scissors Uñas

    = render 'form'

app/views/admin/nails/show.html.haml
.row
  .col-lg-12
    %h1.page-header Uñas
    %ol.breadcrumb
      %li.active
        %i.fa.fa-scissors Uñas

    .text-center
      %h2= @nail.name
      = image_tag @nail.image(:thumb)
      %br

      %h3= "Duración: #{@nail.duration}"
      %h3= "Costo: #{@nail.cost}"
      %h3= "Detalle: #{@nail.detail}"
      %h3= "Número de veces asignado: "


      = link_to 'Editar', edit_admin_nail_path(@nail), class: 'btn btn-success'
      = link_to 'Eliminar', admin_nail_path(@nail), method: :delete, class: 'btn btn-danger'