config/routes.rb
Rails.application.routes.draw do

  get 'no_admin/show'

  devise_for :users, :controllers => {
      :omniauth_callbacks => "omniauth_callbacks",
      :registrations => 'users/registrations',
      :sessions => 'users/sessions'
  }

  root 'landing#home'

  namespace :landing do
    resources :hairstyles, only: [:index, :show] do
      resources :offices, only: [:index] do
        member do
          get :checkout
        end
      end
    end

    resources :makeups, only: [:index, :show] do
      resources :offices, only: [:index] do
        get :checkout
      end
    end

    resources :nails, only: [:index, :show] do
      resources :offices, only: [:index] do
        get :checkout
      end
    end

  end


  namespace :admin do
    resources :offices
    resources :employees
    resources :hairstyles
    resources :makeups
    resources :nails
  end

end

app/models/makeup.rb
class Makeup < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300#", thumb: "100x100#" }, default_url: "makeup.jpg",
                    :url => ':s3_domain_url', :path => '/:class/:attachment/:id_partition/:style/:filename'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates_presence_of :name, :duration, :cost
end

app/controllers/admin/makeups_controller.rb
class Admin::MakeupsController < ApplicationController
  include AdminValidation
  before_action :authenticate_user!, :is_admin?
  before_action :get_makeup, except: [:index, :create, :new]

  def index
    @makeups = Makeup.all
  end

  def new
    @makeup = Makeup.new
  end

  def create
    @makeup = Makeup.new(makeup_params)

    if @makeup.save
      redirect_to [:admin, @makeup]
    else
      render new_admin_makeup_path
    end
  end

  def show
  end

  def edit
  end

  def update
    @makeup.update(makeup_params)
    if @makeup.persisted?
      flash[:notice] = "Se ha actualizado exitosamente"
      redirect_to admin_makeup_path
    end
  end


  def destroy
    @makeup.destroy!
    redirect_to admin_makeups_path
  end

  private

  def get_makeup
    @makeup = Makeup.find(params[:id])
  end

  def makeup_params
    params.require(:makeup).permit(:name, :duration, :cost, :avatar)
  end
end

app/controllers/landing/makeups_controller.rb
class Landing::MakeupsController < ApplicationController
  layout 'salon'

  def index
    @makeups = Makeup.all
  end
end

app/helpers/admin/makeups_helper.rb
module Admin::MakeupsHelper
end

app/views/admin/makeups/_form.html.haml
.container
  .well
    = form_for([:admin, @makeup ], html: { class: 'form-horizontal' }) do |f|
      .form-group
        = f.label 'Nombre'
        = f.text_field :name, class: 'form-control'

      .form-group
        = f.label 'Duración'
        = f.text_field :duration, class: 'form-control'

      .form-group
        = f.label 'Costo'
        = f.text_field :cost, class: 'form-control'

      .form-group
        = f.label 'Imagen'
        = f.file_field :avatar

      = f.submit 'Guardar', class: 'btn btn-success'

app/views/admin/makeups/edit.html.haml
.row
  .col-lg-12
    %h1.page-header Editar maquillaje
    %ol.breadcrumb
      %li.active
        %i.fa.fa-paint-brush Maquillajes

    = render 'form'

app/views/admin/makeups/index.html.haml
.row
  .col-lg-12
    %h1.page-header Lista de Maquillajes
    %ol.breadcrumb
      %li.active
        %i.fa.fa-scissors Maquillajes

    .table-responsive
      %table.table.table-bordered.table-hover.table-striped
        %thead
          %tr
            %th
            %th Nombre
            %th Duración
            %th Costo
        %tbody

        %tbody
          - @makeups.each do |makeup|
            %tr
              %td
                = image_tag makeup.avatar.url(:thumb)
              %td
                = link_to makeup.name, admin_makeup_path(makeup)
              %td
                = makeup.duration
              %td
                = makeup.cost

app/views/admin/makeups/new.html.haml
.row
  .col-lg-12
    %h1.page-header Crear Maquillaje
    %ol.breadcrumb
      %li.active
        %i.fa.fa-paint-brush Maquillaje

    = render 'form'

app/views/admin/makeups/show.html.haml
.row
  .col-lg-12
    %h1.page-header Maquillaje
    %ol.breadcrumb
      %li.active
        %i.fa.fa-paint-brush Maquillajes

    .text-center
      %h2= @makeup.name
      = image_tag @makeup.avatar.url(:medium)
      %br

      %h3= "Duración: #{@makeup.duration}"
      %h3= "Costo: #{@makeup.cost}"
      %h3= "Número de veces asignado: "


      = link_to 'Editar', edit_admin_makeup_path(@makeup), class: 'btn btn-success'
      = link_to 'Eliminar', admin_makeup_path(@makeup), method: :delete, class: 'btn btn-danger'