config/routes.rb
Rails.application.routes.draw do

  get 'no_admin/show'

  devise_for :users, :controllers => {
      :omniauth_callbacks => "omniauth_callbacks",
      :registrations => 'users/registrations',
      :sessions => 'users/sessions'
  }

  root 'landing#home'

  namespace :landing do
    resources :hairstyles, only: [:index, :show] do
      resources :offices, only: [:index] do
        member do
          get :checkout
        end
      end
    end

    resources :makeups, only: [:index, :show] do
      resources :offices, only: [:index] do
        get :checkout
      end
    end

    resources :nails, only: [:index, :show] do
      resources :offices, only: [:index] do
        get :checkout
      end
    end

  end


  namespace :admin do
    resources :offices
    resources :employees
    resources :hairstyles
    resources :makeups
    resources :nails
  end

end

app/models/hairstyle.rb
class Hairstyle < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300#", thumb: "100x100#" }, default_url: "hairstyle.jpg",
                    :url => ':s3_domain_url', :path => '/:class/:attachment/:id_partition/:style/:filename'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_presence_of :name, :duration, :cost, :detail
end

app/controllers/admin/hairstyles_controller.rb
class Admin::HairstylesController < ApplicationController
  include AdminValidation
  before_action :authenticate_user!, :is_admin?
  before_action :get_hairstyle, except: [:index, :create, :new]

  def index
    @hairstyles = Hairstyle.all
  end

  def new
    @hairstyle = Hairstyle.new
  end

  def create
    @hairstyle = Hairstyle.new(hairstyle_params)

    if @hairstyle.save
      redirect_to [:admin, @hairstyle]
    else
      render new_admin_hairstyle_path
    end
  end

  def show
  end

  def edit
  end

  def update
    @hairstyle.update(hairstyle_params)
    if @hairstyle.persisted?
      flash[:notice] = "Se ha actualizado exitosamente"
      redirect_to admin_hairstyle_path
    end
  end


  def destroy
    @hairstyle.destroy!
    redirect_to admin_hairstyles_path
  end

  private

  def get_hairstyle
    @hairstyle = Hairstyle.find(params[:id])
  end

  def hairstyle_params
    params.require(:hairstyle).permit(:name, :duration, :cost, :detail, :image)
  end
end

app/controllers/landing/hairstyles_controller.rb
class Landing::HairstylesController < ApplicationController
  layout 'salon'

  def index
    @hairstyles = Hairstyle.all
  end
end

app/helpers/admin/hairstyles_helper.rb
module Admin::HairstylesHelper
end

app/views/admin/hairstyles/_form.html.haml
.container
  .well
    = form_for([:admin, @hairstyle ], html: { class: 'form-horizontal' }) do |f|
      .form-group
        = f.label 'Nombre'
        = f.text_field :name, class: 'form-control'

      .form-group
        = f.label 'Duración'
        = f.text_field :duration, class: 'form-control'

      .form-group
        = f.label 'Costo'
        = f.text_field :cost, class: 'form-control'

      .form-group
        = f.label 'Detalle'
        = f.text_area :detail, class: 'form-control'

      .form-group
        = f.label 'Imagen'
        = f.file_field :image

      = f.submit 'Guardar', class: 'btn btn-success'

app/views/admin/hairstyles/edit.html.haml
.row
  .col-lg-12
    %h1.page-header Editar peinado
    %ol.breadcrumb
      %li.active
        %i.fa.fa-scissors Peinados

    = render 'form'

app/views/admin/hairstyles/index.html.haml
.row
  .col-lg-12
    %h1.page-header Lista de peinados
    %ol.breadcrumb
      %li.active
        %i.fa.fa-scissors Peinados

    .table-responsive
      %table.table.table-bordered.table-hover.table-striped
        %thead
          %tr
            %th
            %th Nombre
            %th Duración
            %th Costo
            %th Detalle
        %tbody

        %tbody
          - @hairstyles.each do |hairstyle|
            %tr
              %td
                = image_tag 'hairstyle.jpg'
              %td
                = link_to hairstyle.name, admin_hairstyle_path(hairstyle)
              %td
                = hairstyle.duration
              %td
                = hairstyle.cost
              %td
                = hairstyle.detail

app/views/admin/hairstyles/new.html.haml
.row
  .col-lg-12
    %h1.page-header Crear Peinado
    %ol.breadcrumb
      %li.active
        %i.fa.fa-scissors Peinado

    = render 'form'

app/views/admin/hairstyles/show.html.haml
.row
  .col-lg-12
    %h1.page-header Peinado
    %ol.breadcrumb
      %li.active
        %i.fa.fa-scissors Peinados

    .text-center
      %h2= @hairstyle.name
      = image_tag @hairstyle.image(:thumb)
      %br

      %h3= "Duración: #{@hairstyle.duration}"
      %h3= "Costo: #{@hairstyle.cost}"
      %h3= "Detalle: #{@hairstyle.detail}"
      %h3= "Número de veces asignado: "


      = link_to 'Editar', edit_admin_hairstyle_path(@hairstyle), class: 'btn btn-success'
      = link_to 'Eliminar', admin_hairstyle_path(@hairstyle), method: :delete, class: 'btn btn-danger'