config/routes.rb
Rails.application.routes.draw do

  get 'no_admin/show'

  devise_for :users, :controllers => {
      :omniauth_callbacks => "omniauth_callbacks",
      :registrations => 'users/registrations',
      :sessions => 'users/sessions'
  }

  root 'landing#home'

  namespace :landing do
    resources :hairstyles, only: [:index, :show] do
      resources :offices, only: [:index] do
        member do
          get :checkout
        end
      end
    end

    resources :makeups, only: [:index, :show] do
      resources :offices, only: [:index] do
        get :checkout
      end
    end

    resources :nails, only: [:index, :show] do
      resources :offices, only: [:index] do
        get :checkout
      end
    end

  end


  namespace :admin do
    resources :offices
    resources :employees
    resources :hairstyles
    resources :makeups
    resources :nails
  end

end

app/views/layouts/_navbar.html.haml
.navbar-header
  - if user_signed_in? && current_user.is_admin?
    = link_to "Biu Biu - Gestión", root_path, class: "navbar-brand"
  - else
    = link_to "Biu Biu", root_path, class: "navbar-brand"

.navbar-collapse.collapse#navbar-main
  %ul.nav.navbar-nav.navbar-right.top-nav
    - if user_signed_in?
      -#%li= link_to "Account", user_path(current_user), id: "account"
      %li.dropdown
        = link_to '#', class: 'dropdown-toggle', 'data-toggle': 'dropdown', 'aria-expanded': 'false' do
          %i.fa.fa-user &nbsp;Elia Gonzalez
          %b.caret
          %ul.dropdown-menu
            %li
              = link_to '#' do
                %i.fa.fa-fw.fa-user &nbsp;Perfil
            %li.divider
            %li
              = link_to destroy_user_session_path, method: 'delete' do
                %i.fa.fa-fw.fa-power-off &nbsp;Cerrar sesión
    - else
      %li= link_to "Ingreso", new_user_session_path
      %li= link_to "Registrar", new_user_registration_path

app/views/layouts/_sidebar.html.haml
.collapse.navbar-collapse.navbar-ex1-collapse
  %ul.nav.navbar-nav.side-nav
    %li
      = link_to 'javascript:;', 'data-toggle': 'collapse', 'data-target': '#estilistas', 'aria-expanded': 'false'  do
        %i.fa.fa-fw.fa-user &nbsp;Estilistas
        %i.fa.fa-fw.fa-caret-down.caret-right
      %ul#estilistas.nav.nav-second-level.collapse{'aria-expanded': 'false'}
        %li
          = link_to 'Agregar', new_admin_employee_path
        %li
          = link_to 'Mis agentes', admin_employees_path
    %li
      = link_to 'javascript:;', 'data-toggle': 'collapse', 'data-target': '#peinados', 'aria-expanded': 'false'  do
        %i.fa.fa-fw.fa-scissors &nbsp;Peinados
        %i.fa.fa-fw.fa-caret-down.caret-right
      %ul#peinados.nav.nav-second-level.collapse{'aria-expanded': 'false'}
        %li
          = link_to 'Agregar', new_admin_hairstyle_path
        %li
          = link_to 'Mis peinados', admin_hairstyles_path
    %li
      = link_to 'javascript:;', 'data-toggle': 'collapse', 'data-target': '#maquillaje', 'aria-expanded': 'false'  do
        %i.fa.fa-fw.fa-paint-brush &nbsp;Maquillaje
        %i.fa.fa-fw.fa-caret-down.caret-right
      %ul#maquillaje.nav.nav-second-level.collapse{'aria-expanded': 'false'}
        %li
          = link_to 'Agregar', new_admin_makeup_path
        %li
          = link_to 'Mis maquillajes', admin_makeups_path
    %li
      = link_to 'javascript:;', 'data-toggle': 'collapse', 'data-target': '#unas', 'aria-expanded': 'false'  do
        %i.fa.fa-fw.fa-tint &nbsp;Uñas
        %i.fa.fa-fw.fa-caret-down.caret-right
      %ul#unas.nav.nav-second-level.collapse{'aria-expanded': 'false'}
        %li
          = link_to 'Agregar', new_admin_nail_path
        %li
          = link_to 'Mis uñas', admin_nails_path
    %li
      = link_to 'javascript:;', 'data-toggle': 'collapse', 'data-target': '#salones', 'aria-expanded': 'false'  do
        %i.fa.fa-fw.fa-building &nbsp;Salones
        %i.fa.fa-fw.fa-caret-down.caret-right
      %ul#salones.nav.nav-second-level.collapse{'aria-expanded': 'false'}
        %li
          = link_to 'Agregar', new_admin_office_path
        %li
          = link_to 'Mis salones', admin_offices_path
    %li
      = link_to root_path do
        %i.fa.fa-fw.fa-users &nbsp;Clientes
    %li
      = link_to root_path do
        %i.fa.fa-fw.fa-check-square-o &nbsp;Citas
    %li
      = link_to root_path do
        %i.fa.fa-fw.fa-pie-chart &nbsp;Balance de ingresos

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Biubiu
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    <!-- Custom CSS -->
    = stylesheet_link_tag 'sb-admin'

    <!-- Custom Fonts -->
    = stylesheet_link_tag '/font-awesome/css/font-awesome.min'

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    %script{src: "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"}
    %script{src: "https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"}
    <![endif]-->
    = csrf_meta_tags
  %body
    #wrapper
      %nav.navbar.navbar-inverse.navbar-fixed-top
        .container-fluid
          = render 'layouts/navbar'
          - if user_signed_in? && current_user.is_admin
            = render 'layouts/sidebar'

      #page-wrapper
        .container-fluid#main

          = yield
          = debug(params) if Rails.env.development?

    :javascript
      toastr.options = {
        positionClass: "toast-top-left",
        timeout: "2000",
        extendedTimeout: "2000",
      }

    %script{:src => 'js/bootstrap.min.js'}

    = custom_flash_messages

app/views/layouts/salon.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Biubiu
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    <!-- Custom CSS -->
    = stylesheet_link_tag 'sb-admin'

    <!-- Custom Fonts -->
    = stylesheet_link_tag '/font-awesome/css/font-awesome.min'

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    %script{src: "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"}
    %script{src: "https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"}
    <![endif]-->
    = csrf_meta_tags
  %body
    %div
      %nav.navbar.navbar-inverse.navbar-fixed-top
        .container-fluid
          = render 'layouts/navbar'
          - if user_signed_in? && current_user.is_admin
            = render 'layouts/sidebar'

      #page-wrapper
        .container-fluid#main

          = yield
          = debug(params) if Rails.env.development?

    :javascript
      toastr.options = {
        positionClass: "toast-top-left",
        timeout: "2000",
        extendedTimeout: "2000",
      }

    %script{:src => 'js/bootstrap.min.js'}

    = custom_flash_messages